import './style.css';
import { Chess } from 'chess.js';
import { createClient } from '@supabase/supabase-js';
import { initialClocks, normalizeRoomId } from './game-config.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const params=new URLSearchParams(location.search), generatedRoom=Math.random().toString(36).slice(2,10).toUpperCase(), room=normalizeRoomId(params.get('game'),generatedRoom);
const sbUrl=import.meta.env.VITE_SUPABASE_URL, sbKey=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=sbUrl&&sbKey?createClient(sbUrl,sbKey):null;
const game=new Chess(); let selected=null, flipped=false, mode='room', myColor=null, ticking, channel, enginePending;
const playerToken=localStorage.getItem('vanta-player-token')||crypto.randomUUID();
localStorage.setItem('vanta-player-token',playerToken);
const stockfish=new Worker('/stockfish.worker.js');
stockfish.onmessage=({data})=>{if(data.type==='uci'&&data.line.startsWith('bestmove ')){const u=data.line.split(' ')[1];enginePending?.(u);enginePending=null}else if(data.type==='unavailable'&&enginePending){enginePending(null);enginePending=null}};
const glyph={wk:'♔',wq:'♕',wr:'♖',wb:'♗',wn:'♘',wp:'♙',bk:'♚',bq:'♛',br:'♜',bb:'♝',bn:'♞',bp:'♟'};
const app=$('#app');
app.innerHTML=`
<div class="shell"><header><a class="brand"><span class="mark">V</span><b>VANTA<br>CHESS</b></a><nav><button class="active">♞ <span>Play</span></button><button>♛ <span>Arena</span></button><button>♟ <span>Puzzles</span></button><button>▤ <span>Learn</span></button><button>♜ <span>Openings</span></button></nav><div class="user"><i></i><span>Guest-${room.slice(-4)}</span><small>1200 rating</small></div></header>
<main><aside class="lpanel panel"><div class="hero"><label>● &nbsp; LIVE CHESS</label><h1>Play your<br>next game.</h1><p>Guest play is instant. Rated games save your Elo and tournament record.</p></div><div class="modes"><button data-mode="match">⚡<span>Match</span></button><button data-mode="room" class="on">♟<span>Room</span></button><button data-mode="computer">▣<span>Computer</span></button></div><section><h3>Create a private room</h3><p>Generate a shareable game link instantly.</p></section><label class="tiny">GAME SETTINGS</label><div class="settings"><select id="time"><option value="600">◷ 10+0 Rapid</option><option value="300">◷ 5+0 Blitz</option><option value="180">◷ 3+0 Blitz</option></select><select id="level"><option value="1200">Casual · 1200</option><option value="1600">Club · 1600</option><option value="2000">Expert · 2000</option></select></div><button class="gold" id="create">Create room & get link <b>＋</b></button><div class="divider">or join an existing room</div><div class="join"><input id="roomInput" placeholder="Enter room code"><button id="join">Join room</button></div><div class="room"><small>ROOM CODE</small><strong>${room}</strong><em>● Ready</em><p>Share this link</p><div><input id="share" readonly value="${location.origin+location.pathname}?game=${room}"><button id="copy">▣</button></div></div></aside>
<section class="game"><div class="player top"><span class="avatar">GU</span><div><b>Guest-Opponent</b><small>☆ 1200</small></div><i class="signal">▥ 42 ms</i><time id="blackClock">10:00</time></div><div id="board" class="board" aria-label="Chess board"></div><div class="player bottom"><span class="avatar light">GU</span><div><b>You · Guest-${room.slice(-4)}</b><small>☆ 1200</small></div><i class="signal">▥ connected</i><time id="whiteClock">10:00</time></div><div class="tools"><button id="flip">⇄ Flip board</button><button id="sound">♫ Sound on</button><button id="theme">▦ Board theme</button><button id="resign" class="danger">⚑ Resign</button></div></section>
<aside class="rpanel panel"><div class="tabs"><button class="on">Moves</button><button>Analysis</button><button>Openings</button></div><div class="status"><small>● &nbsp; LIVE GAME</small><h2 id="turn">White to move</h2><p id="state">Real time &nbsp;•&nbsp; Casual game</p></div><div id="moves" class="moves"><span>Game ready — make a move.</span></div><section class="analysis"><header><b>▣ Engine Analysis</b><small>Stockfish 19 · Elo <span id="elo">1200</span></small></header><h2 id="score">+0.0</h2><div class="meter"><i></i></div><p id="line">Analysis begins after your move.</p></section><section class="chat"><h3>Player chat</h3><div id="messages"></div><form id="chat"><input id="message" maxlength="160" placeholder="Send a friendly message…"><button>Send</button></form></section><div class="cards"><article><b>♛ Arena</b><p>Live tournaments and events from Vanta.</p></article><article><b>◎ Daily Puzzle</b><p>Sharpen tactics with a new position.</p></article></div></aside></main></div><div id="toast"></div><dialog id="promotion"><h2>Promote pawn</h2><div><button data-piece="q">♕</button><button data-piece="r">♖</button><button data-piece="b">♗</button><button data-piece="n">♘</button></div></dialog>`;

let clocks=initialClocks(Number($('#time').value));
function render(){const board=$('#board'), order=flipped?[...Array(64).keys()].reverse():[...Array(64).keys()]; board.innerHTML=''; const pos=game.board().flat(); const legal=selected?game.moves({square:selected,verbose:true}):[]; order.forEach(i=>{const r=Math.floor(i/8),f=i%8,sq='abcdefgh'[f]+(8-r),p=pos[i],el=document.createElement('button');el.className=`square ${(r+f)%2?'dark':'light'} ${selected===sq?'selected':''} ${legal.some(m=>m.to===sq)?'legal':''}`;el.dataset.sq=sq;el.setAttribute('aria-label',sq+(p?' '+p.color+p.type:'')); if(p)el.innerHTML=`<span class="piece ${p.color}">${glyph[p.color+p.type]}</span>`; if(f===(flipped?7:0))el.insertAdjacentHTML('beforeend',`<small class="rank">${8-r}</small>`);if(r===(flipped?0:7))el.insertAdjacentHTML('beforeend',`<small class="file">${'abcdefgh'[f]}</small>`);el.onclick=()=>clickSquare(sq,p); board.append(el)}); $('#turn').textContent=game.isGameOver()?endText():`${game.turn()==='w'?'White':'Black'} to move`; $('#state').textContent=game.inCheck()?'Check · Real time':'Real time  •  Casual game';}
function endText(){if(game.isCheckmate())return `Checkmate · ${game.turn()==='w'?'Black':'White'} wins`;if(game.isStalemate())return 'Draw · Stalemate';if(game.isThreefoldRepetition())return 'Draw · Repetition';return 'Draw';}
async function clickSquare(sq,p){if(game.isGameOver()||(supabase&&mode==='room'&&myColor!==game.turn()))return;if(!selected){if(p?.color===game.turn()){selected=sq;render()}return} if(p?.color===game.turn()){selected=sq;render();return} const candidates=game.moves({square:selected,verbose:true}).filter(m=>m.to===sq);if(!candidates.length){selected=null;render();return}let promotion;if(candidates.some(m=>m.promotion))promotion=await choosePromotion();makeMove({from:selected,to:sq,promotion:promotion||'q'});selected=null;}
function choosePromotion(){return new Promise(resolve=>{const d=$('#promotion');d.showModal();$$('#promotion button').forEach(b=>b.onclick=()=>{d.close();resolve(b.dataset.piece)})})}
async function makeMove(move,remote=false){let made;try{made=game.move(move)}catch{return} render();updateMoves();playTone();if(supabase&&!remote){const {error}=await supabase.rpc('play_move',{game_id:room,expected_ply:game.history().length-1,san:made.san,next_fen:game.fen(),player_token:playerToken});if(error){toast('Move rejected · restoring server state');await restoreServerState()}}if(mode==='computer'&&!game.isGameOver())setTimeout(engineMove,280);}
function updateMoves(){const h=game.history();$('#moves').innerHTML=h.length?h.map((m,i)=>i%2===0?`<div><b>${i/2+1}.</b><span>${m}</span><span>${h[i+1]||''}</span></div>`:'').join(''):'<span>Game ready — make a move.</span>';$('#moves').scrollTop=9999}
async function engineMove(){const moves=game.moves({verbose:true});if(!moves.length)return;const uci=await new Promise(resolve=>{enginePending=resolve;stockfish.postMessage({fen:game.fen(),elo:Number($('#level').value),movetime:350});setTimeout(()=>{if(enginePending){enginePending(null);enginePending=null}},1200)});let m=uci&&moves.find(x=>x.from+x.to+(x.promotion||'')===uci);if(!m){const captures=moves.filter(x=>x.captured);m=(captures.length?captures:moves)[Math.floor(Math.random()*(captures.length||moves.length))]}makeMove(m,true)}
function playTone(){if($('#sound').dataset.off)return;const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=420;g.gain.setValueAtTime(.05,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.09);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.1)}
function clockText(n){return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`}
function startClock(){clearInterval(ticking);ticking=setInterval(()=>{if(game.history().length&&!game.isGameOver()){clocks[game.turn()]--;$('#whiteClock').textContent=clockText(clocks.w);$('#blackClock').textContent=clockText(clocks.b);if(clocks[game.turn()]<=0){clearInterval(ticking);$('#turn').textContent=`Time · ${game.turn()==='w'?'Black':'White'} wins`}}},1000)}
function toast(s){$('#toast').textContent=s;$('#toast').className='show';setTimeout(()=>$('#toast').className='',1800)}
async function restoreServerState(){const {data}=await supabase.from('moves').select('move').eq('room_id',room).order('ply');game.reset();for(const item of data||[]){try{game.move(item.move)}catch{break}}render();updateMoves()}
async function connect(){if(!supabase){myColor='w';toast('Local room · add Supabase keys for online sync');return}await supabase.from('games').insert({id:room}).select().maybeSingle();const {data:seat,error:seatError}=await supabase.rpc('claim_game_seat',{game_id:room,player_token:playerToken});myColor=seatError?null:seat;channel=supabase.channel(`room:${room}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'moves',filter:`room_id=eq.${room}`},p=>{if(p.new.ply===game.history().length+1)makeMove(p.new.move,true);else if(p.new.ply>game.history().length+1)restoreServerState()}).on('broadcast',{event:'chat'},({payload})=>addMessage(payload.text,false)).subscribe();await restoreServerState();toast(myColor?`You are playing ${myColor==='w'?'White':'Black'}`:'Room full · spectating')}
function addMessage(text,mine=true){const e=document.createElement('p');e.className=mine?'mine':'';e.textContent=text;$('#messages').append(e);e.scrollIntoView()}
$('#chat').onsubmit=e=>{e.preventDefault();const v=$('#message').value.trim();if(!v)return;addMessage(v);channel?.send({type:'broadcast',event:'chat',payload:{text:v}});$('#message').value=''};
$$('.modes button').forEach(b=>b.onclick=()=>{$$('.modes button').forEach(x=>x.classList.remove('on'));b.classList.add('on');mode=b.dataset.mode;if(mode==='computer')toast('Computer opponent ready');if(mode==='match'){toast('Searching… engine fallback in 15 seconds');setTimeout(()=>{mode='computer';toast('Closest engine opponent found · 1200 Elo')},15000)}});
$('#flip').onclick=()=>{flipped=!flipped;render()};$('#sound').onclick=e=>{e.currentTarget.dataset.off=e.currentTarget.dataset.off?'':'1';e.currentTarget.textContent=e.currentTarget.dataset.off?'♫ Sound off':'♫ Sound on'};$('#theme').onclick=()=>document.body.classList.toggle('violet');$('#resign').onclick=()=>{if(confirm('Resign this game?')){$('#turn').textContent='You resigned';clearInterval(ticking)}};$('#copy').onclick=async()=>{await navigator.clipboard.writeText($('#share').value);toast('Room link copied')};$('#create').onclick=()=>{$('#share').select();toast('Private room is ready')};$('#join').onclick=()=>{const v=$('#roomInput').value.trim();if(v)location.search='?game='+encodeURIComponent(v)};$('#level').onchange=e=>$('#elo').textContent=e.target.value;
$('#time').onchange=e=>{if(game.history().length)return toast('Time control cannot change after the first move');clocks=initialClocks(Number(e.target.value));$('#whiteClock').textContent=clockText(clocks.w);$('#blackClock').textContent=clockText(clocks.b)};
render();startClock();connect();
